# Generated by Django 5.2.14 on 2026-09-24 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M2MApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(db_index=True, max_length=8, unique=True)),
                ('hashed_key', models.CharField(max_length=64)),
                ('intended_use', models.TextField()),
                ('terms_version', models.CharField(max_length=32)),
                ('terms_accepted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, default='', max_length=64)),
                ('rate_tier', models.CharField(choices=[('standard', 'Standard'), ('elevated', 'Elevated')], default='standard', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m2m_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M2M API key',
                'verbose_name_plural': 'M2M API keys',
            },
        ),
        migrations.CreateModel(
            name='M2MApiKeyUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_days', to='m2m_api.m2mapikey')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'date'), name='m2m_usage_key_date_unique')],
            },
        ),
    ]
