# Generated by Django 5.2.14 on 2026-05-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meshcore_packets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='meshcorerawpacket',
            new_name='meshcore_pa_from_pu_8e7820_idx',
            old_name='meshcore_raw_prefix_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='meshcorerawpacket',
            new_name='meshcore_pa_rx_time_ccc9d3_idx',
            old_name='meshcore_raw_rx_time_idx',
        ),
    ]
