# Generated by Django 5.2.14 on 2026-06-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshcore_packets', '0003_remove_meshcorerawpacket_path_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='meshcorepacketobservation',
            name='path_hash_mode',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meshcorepacketobservation',
            name='path_hash_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
