# Generated by Django 5.2 on 2025-05-02 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constellations', '0003_messagechannel'),
        ('nodes', '0012_managednode_channel_0_managednode_channel_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_node_id', models.BigIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_text', models.TextField()),
                ('is_emoji', models.BooleanField(default=False)),
                ('reply_to_message_id', models.BigIntegerField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constellations.messagechannel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.observednode')),
            ],
            options={
                'verbose_name': 'Text message',
                'verbose_name_plural': 'Text messages',
            },
        ),
    ]
