# Generated by Django 5.2 on 2025-05-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_messages', '0002_alter_textmessage_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='packet_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
