# Generated by Django 5.2 on 2025-05-12 21:15

import django.db.models.deletion
from django.db import migrations, models

def link_packets(apps, schema_editor):
    TextMessage = apps.get_model('text_messages', 'TextMessage')
    MessagePacket = apps.get_model('packets', 'MessagePacket')
    for msg in TextMessage.objects.all():
        try:
            packet = MessagePacket.objects.get(packet_id=msg.packet_id)
            msg.original_packet = packet
            msg.save(update_fields=['original_packet'])
        except MessagePacket.DoesNotExist:
            # Not much we can do here
            pass
        except MessagePacket.MultipleObjectsReturned:
            # We sometimes got mutiple observations in early versions
            # this shouldn't happen in prod, but if it does it's not the end of the world
            # so we'll just take the first one
            packet = MessagePacket.objects.filter(packet_id=msg.packet_id).first()
            msg.original_packet = packet
            msg.save(update_fields=['original_packet'])
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0003_rawpacket_first_reported_time'),
        ('text_messages', '0003_textmessage_packet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='original_packet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packets.messagepacket'),
        ),
        migrations.RunPython(link_packets, reverse_code=migrations.RunPython.noop),
    ]
