# Generated by Django 5.2 on 2025-05-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_messages', '0004_textmessage_original_packet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessage',
            name='packet_id',
        ),
    ]
