# Generated by Django 5.2.14 on 2026-05-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0017_rename_rawpacket_to_mtrawpacket'),
        ('text_messages', '0005_remove_textmessage_packet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='original_packet',
            field=models.ForeignKey(help_text='Provenance: Meshtastic ``MessagePacket`` today. Phase 2 may split into ``original_mt_packet`` / ``original_mc_packet`` FKs without renaming this column.', null=True, on_delete=django.db.models.deletion.CASCADE, to='packets.messagepacket'),
        ),
    ]
