# Generated by Django 5.2.12 on 2026-03-12 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0023_remove_observednode_sw_version'),
        ('packets', '0015_rename_packets_raw_from_pkt_idx_packets_raw_from_in_81757d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTraceRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('auto', 'Auto'), ('user', 'User')], max_length=16)),
                ('trigger_source', models.CharField(blank=True, help_text='e.g. scheduler', max_length=32, null=True)),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('route', models.JSONField(blank=True, help_text='List of {node_id, snr} from TR response', null=True)),
                ('route_back', models.JSONField(blank=True, help_text='List of {node_id, snr} from TR response (return path)', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_traceroutes', to='packets.traceroutepacket')),
                ('source_node', models.ForeignKey(help_text='Node that sent the TR (source)', on_delete=django.db.models.deletion.CASCADE, related_name='traceroutes_sent', to='nodes.managednode')),
                ('target_node', models.ForeignKey(help_text='Destination node', on_delete=django.db.models.deletion.CASCADE, related_name='traceroutes_received', to='nodes.observednode')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered (manual only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_traceroutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auto traceroute',
                'verbose_name_plural': 'Auto traceroutes',
                'permissions': [('trigger_traceroute', 'Can trigger traceroute commands')],
                'indexes': [models.Index(fields=['source_node'], name='traceroute__source__d64776_idx'), models.Index(fields=['target_node'], name='traceroute__target__1ed78f_idx'), models.Index(fields=['triggered_at'], name='traceroute__trigger_9b832e_idx'), models.Index(fields=['status'], name='traceroute__status_c18d07_idx')],
            },
        ),
    ]
