# Generated by Django 5.2.12 on 2026-03-12 23:38

from django.db import migrations, models


def create_mark_stale_task(apps, schema_editor):
    """Create PeriodicTask to run mark_stale_traceroutes_failed every minute."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="*",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        defaults={"timezone": "UTC"},
    )

    PeriodicTask.objects.get_or_create(
        name="mark_stale_traceroutes_failed",
        defaults={
            "task": "traceroute.tasks.mark_stale_traceroutes_failed",
            "crontab": schedule,
            "enabled": True,
        },
    )


def remove_mark_stale_task(apps, schema_editor):
    """Remove the mark_stale_traceroutes_failed PeriodicTask."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="mark_stale_traceroutes_failed").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("traceroute", "0002_add_schedule_traceroutes_periodic_task"),
        ("django_celery_beat", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="autotraceroute",
            index=models.Index(fields=["status", "triggered_at"], name="traceroute__status_6c346c_idx"),
        ),
        migrations.RunPython(create_mark_stale_task, remove_mark_stale_task),
    ]
