# Generated by Django 5.2.12 on 2026-03-13

from django.db import migrations


def mark_empty_route_completed_as_failed(apps, schema_editor):
    """
    Mark AutoTraceRoute records as failed when they are currently 'completed'
    but both route and route_back are empty (timed out / empty response from device).
    """
    AutoTraceRoute = apps.get_model("traceroute", "AutoTraceRoute")
    to_update = []
    for tr in AutoTraceRoute.objects.filter(status="completed"):
        route_empty = tr.route is None or tr.route == []
        route_back_empty = tr.route_back is None or tr.route_back == []
        if route_empty and route_back_empty:
            tr.status = "failed"
            tr.error_message = "Timed out (empty route from device)"
            to_update.append(tr)
    if to_update:
        AutoTraceRoute.objects.bulk_update(to_update, ["status", "error_message"])


def noop_reverse(apps, schema_editor):
    """Data migration cannot be reversed meaningfully."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("traceroute", "0003_add_stale_tr_task_and_index"),
    ]

    operations = [
        migrations.RunPython(mark_empty_route_completed_as_failed, noop_reverse),
    ]
