# Generated by Django 5.2.12 on 2026-03-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceroute', '0004_fix_empty_route_completed_as_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotraceroute',
            name='trigger_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('user', 'User'), ('external', 'External')], max_length=16),
        ),
    ]
