# Generated by Django 5.2.13 on 2026-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceroute', '0006_add_collect_traceroute_success_daily_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotraceroute',
            name='trigger_type',
            field=models.CharField(choices=[('auto', 'Auto'), ('user', 'User'), ('external', 'External'), ('monitor', 'Monitor')], max_length=16),
        ),
    ]
