# Generated by Django 5.2.13 on 2026-04-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceroute', '0008_target_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotraceroute',
            name='target_strategy',
            field=models.CharField(blank=True, choices=[('intra_zone', 'Intra zone'), ('dx_across', 'DX across'), ('dx_same_side', 'DX same side'), ('legacy', 'Legacy / unspecified'), ('manual', 'Manual target')], db_index=True, help_text='Hypothesis-driven target selection strategy (scheduler or manual analytics)', max_length=24, null=True),
        ),
    ]
