# Generated by Django 5.2.13 on 2026-04-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_notify_user_id',
            field=models.CharField(blank=True, default='', help_text='Discord snowflake for DM notifications (set only after verified link).', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_notify_verified_at',
            field=models.DateTimeField(blank=True, help_text='When Discord identity was last verified for notifications (OAuth link).', null=True),
        ),
    ]
