# Generated by Django 5.2 on 2025-04-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Constellation',
                'verbose_name_plural': 'Constellations',
            },
        ),
        migrations.CreateModel(
            name='ConstellationUserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=32)),
            ],
            options={
                'verbose_name': 'Constellation membership',
                'verbose_name_plural': 'Constellation memberships',
            },
        ),
    ]
