# Generated by Django 5.2 on 2025-04-22 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constellations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_constellations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constellationusermembership',
            name='constellation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constellations.constellation'),
        ),
        migrations.AddField(
            model_name='constellationusermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='constellationusermembership',
            unique_together={('user', 'constellation')},
        ),
    ]
