# Generated by Django 5.2 on 2025-04-22 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constellation',
            options={'verbose_name': 'Constellation', 'verbose_name_plural': 'Constellations'},
        ),
        migrations.AlterModelOptions(
            name='constellationusermembership',
            options={'verbose_name': 'Constellation membership', 'verbose_name_plural': 'Constellation memberships'},
        ),
        migrations.AlterModelOptions(
            name='nodeapikey',
            options={'verbose_name': 'Node API Key', 'verbose_name_plural': 'Node API Keys'},
        ),
        migrations.AlterModelOptions(
            name='nodeauth',
            options={'verbose_name': 'Node authentication', 'verbose_name_plural': 'Node authentications'},
        ),
        migrations.AddField(
            model_name='nodeapikey',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The user who owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='owned_api_keys', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
