# Generated by Django 5.2 on 2025-05-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constellations.constellation')),
            ],
            options={
                'verbose_name': 'Message channel',
                'verbose_name_plural': 'Message channels',
            },
        ),
    ]
