# Generated by Django 5.2 on 2025-05-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0003_messagechannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='map_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
