# Generated by Django 5.2.12 on 2026-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0004_constellation_map_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='bot_default_hop_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constellation',
            name='bot_default_ignore_portnums',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
