# Generated by Django 5.2.14 on 2026-05-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0006_protocol_fields_messagechannel_constellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constellation',
            name='protocol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Meshtastic'), (2, 'MeshCore')], db_index=True, default=1, help_text='Mesh protocol for this constellation and its channels.'),
        ),
        migrations.AlterField(
            model_name='messagechannel',
            name='protocol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Meshtastic'), (2, 'MeshCore')], db_index=True, default=1, help_text='Mesh protocol for this channel row.'),
        ),
    ]
