# Generated by Django 5.2.14 on 2026-05-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0009_messagechannel_mc_type_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeshCoreMessageChannel',
            fields=[
            ],
            options={
                'verbose_name': 'MeshCore channel',
                'verbose_name_plural': 'MeshCore channels',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('constellations.messagechannel',),
        ),
    ]
