# Generated by Django 5.2 on 2025-04-22 10:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPacket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packet_id', models.BigIntegerField()),
                ('from_int', models.BigIntegerField()),
                ('from_str', models.CharField(max_length=9, null=True)),
                ('to_int', models.BigIntegerField(null=True)),
                ('to_str', models.CharField(max_length=9, null=True)),
                ('port_num', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PacketObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.SmallIntegerField(null=True)),
                ('hop_limit', models.SmallIntegerField(null=True)),
                ('hop_start', models.SmallIntegerField(null=True)),
                ('rx_time', models.DateTimeField()),
                ('rx_rssi', models.FloatField(null=True)),
                ('rx_snr', models.FloatField(null=True)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('relay_node', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceMetricsPacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('reading_time', models.DateTimeField()),
                ('battery_level', models.FloatField(null=True)),
                ('voltage', models.FloatField(null=True)),
                ('channel_utilization', models.FloatField(null=True)),
                ('air_util_tx', models.FloatField(null=True)),
                ('uptime_seconds', models.BigIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('packets.rawpacket',),
        ),
        migrations.CreateModel(
            name='EnvironmentMetricsPacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('reading_time', models.DateTimeField()),
                ('temperature', models.FloatField(null=True)),
                ('relative_humidity', models.FloatField(null=True)),
                ('barometric_pressure', models.FloatField(null=True)),
                ('gas_resistance', models.FloatField(null=True)),
                ('iaq', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('packets.rawpacket',),
        ),
        migrations.CreateModel(
            name='LocalStatsPacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('reading_time', models.DateTimeField()),
                ('uptime_seconds', models.BigIntegerField(null=True)),
                ('channel_utilization', models.FloatField(null=True)),
                ('air_util_tx', models.FloatField(null=True)),
                ('num_packets_tx', models.BigIntegerField(null=True)),
                ('num_packets_rx', models.BigIntegerField(null=True)),
                ('num_packets_rx_bad', models.BigIntegerField(null=True)),
                ('num_online_nodes', models.IntegerField(null=True)),
                ('num_total_nodes', models.IntegerField(null=True)),
                ('num_rx_dupe', models.BigIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('packets.rawpacket',),
        ),
        migrations.CreateModel(
            name='MessagePacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('message_text', models.TextField()),
                ('reply_packet_id', models.BigIntegerField(db_index=True, null=True)),
                ('emoji', models.BooleanField(null=True)),
            ],
            bases=('packets.rawpacket',),
        ),
        migrations.CreateModel(
            name='NodeInfoPacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('node_id', models.CharField(db_index=True, max_length=9, null=True)),
                ('short_name', models.CharField(max_length=5, null=True)),
                ('long_name', models.CharField(max_length=50, null=True)),
                ('hw_model', models.CharField(max_length=50, null=True)),
                ('sw_version', models.CharField(max_length=12, null=True)),
                ('public_key', models.CharField(max_length=64, null=True)),
                ('mac_address', models.CharField(max_length=20, null=True)),
            ],
            bases=('packets.rawpacket',),
        ),
        migrations.CreateModel(
            name='PositionPacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('altitude', models.FloatField(null=True)),
                ('heading', models.FloatField(null=True)),
                ('location_source', models.CharField(max_length=15, null=True)),
                ('precision_bits', models.SmallIntegerField(null=True)),
            ],
            bases=('packets.rawpacket',),
        ),
        migrations.AddIndex(
            model_name='rawpacket',
            index=models.Index(fields=['packet_id'], name='packets_raw_packet__cc40c7_idx'),
        ),
        migrations.AddIndex(
            model_name='rawpacket',
            index=models.Index(fields=['from_int'], name='packets_raw_from_in_3cd2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='rawpacket',
            index=models.Index(fields=['to_int'], name='packets_raw_to_int_52668e_idx'),
        ),
        migrations.AddField(
            model_name='packetobservation',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.meshtasticnode'),
        ),
        migrations.AddField(
            model_name='packetobservation',
            name='packet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packets.rawpacket'),
        ),
    ]
