# Generated by Django 5.2 on 2025-04-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemetricspacket',
            options={'verbose_name': 'Device metrics packet', 'verbose_name_plural': 'Device metrics packets'},
        ),
        migrations.AlterModelOptions(
            name='environmentmetricspacket',
            options={'verbose_name': 'Environment metrics packet', 'verbose_name_plural': 'Environment metrics packets'},
        ),
        migrations.AlterModelOptions(
            name='localstatspacket',
            options={'verbose_name': 'Local stats packet', 'verbose_name_plural': 'Local stats packets'},
        ),
        migrations.AlterModelOptions(
            name='messagepacket',
            options={'verbose_name': 'Message packet', 'verbose_name_plural': 'Message packets'},
        ),
        migrations.AlterModelOptions(
            name='nodeinfopacket',
            options={'verbose_name': 'Node info packet', 'verbose_name_plural': 'Node info packets'},
        ),
        migrations.AlterModelOptions(
            name='packetobservation',
            options={'verbose_name': 'Packet observation', 'verbose_name_plural': 'Packet observations'},
        ),
        migrations.AlterModelOptions(
            name='positionpacket',
            options={'verbose_name': 'Position packet', 'verbose_name_plural': 'Position packets'},
        ),
        migrations.AlterModelOptions(
            name='rawpacket',
            options={'verbose_name': 'Raw packet', 'verbose_name_plural': 'Raw packets'},
        ),
    ]
