# Generated by Django 5.2 on 2025-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfopacket',
            name='role',
            field=models.IntegerField(choices=[(0, 'CLIENT'), (1, 'CLIENT_MUTE'), (2, 'CLIENT_HIDDEN'), (3, 'TRACKER'), (4, 'LOST_AND_FOUND'), (5, 'SENSOR'), (6, 'TAK'), (7, 'TAK_TRACKER'), (8, 'REPEATER'), (9, 'ROUTER'), (10, 'ROUTER_LATE')], null=True),
        ),
        migrations.AddField(
            model_name='positionpacket',
            name='ground_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='positionpacket',
            name='ground_track',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='positionpacket',
            name='position_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='positionpacket',
            name='location_source',
            field=models.IntegerField(choices=[(0, 'UNSET'), (1, 'LOC_MANUAL'), (2, 'LOC_INTERNAL'), (3, 'LOC_EXTERNAL')], null=True),
        ),
    ]
