# Generated by Django 5.2 on 2025-04-30 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0002_alter_packetobservation_packet'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpacket',
            name='first_reported_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
