# Generated by Django 5.2 on 2025-05-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0003_rawpacket_first_reported_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packetobservation',
            old_name='channel',
            new_name='channel_idx',
        ),
    ]
