# Generated by Django 5.2 on 2025-05-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0005_packetobservation_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packetobservation',
            name='channel_idx',
        ),
    ]
