# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0006_remove_packetobservation_channel_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='localstatspacket',
            name='num_tx_relay',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localstatspacket',
            name='num_tx_relay_canceled',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localstatspacket',
            name='heap_total_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localstatspacket',
            name='heap_free_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localstatspacket',
            name='num_tx_dropped',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localstatspacket',
            name='noise_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
