# Generated by Django 5.2.1 on 2025-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0006_remove_packetobservation_channel_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawpacket',
            old_name='first_reported_time',
            new_name='first_observed_time',
        ),
        migrations.AlterField(
            model_name='rawpacket',
            name='first_observed_time',
            field=models.DateTimeField(),  # This removes the default
        ),
    ]
