# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0007_add_localstats_protobuf_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentmetricspacket',
            name='iaq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='lux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='white_lux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='ir_lux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='uv_lux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='wind_direction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='wind_gust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='wind_lull',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='radiation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='rainfall_1h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='rainfall_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='soil_moisture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentmetricspacket',
            name='soil_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
