# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0008_environmentmetrics_protobuf_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityMetricsPacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('reading_time', models.DateTimeField()),
                ('pm10_standard', models.IntegerField(blank=True, null=True)),
                ('pm25_standard', models.IntegerField(blank=True, null=True)),
                ('pm100_standard', models.IntegerField(blank=True, null=True)),
                ('pm10_environmental', models.IntegerField(blank=True, null=True)),
                ('pm25_environmental', models.IntegerField(blank=True, null=True)),
                ('pm100_environmental', models.IntegerField(blank=True, null=True)),
                ('particles_03um', models.IntegerField(blank=True, null=True)),
                ('particles_05um', models.IntegerField(blank=True, null=True)),
                ('particles_10um', models.IntegerField(blank=True, null=True)),
                ('particles_25um', models.IntegerField(blank=True, null=True)),
                ('particles_50um', models.IntegerField(blank=True, null=True)),
                ('particles_100um', models.IntegerField(blank=True, null=True)),
                ('co2', models.IntegerField(blank=True, null=True)),
                ('co2_temperature', models.FloatField(blank=True, null=True)),
                ('co2_humidity', models.FloatField(blank=True, null=True)),
                ('form_formaldehyde', models.FloatField(blank=True, null=True)),
                ('form_humidity', models.FloatField(blank=True, null=True)),
                ('form_temperature', models.FloatField(blank=True, null=True)),
                ('pm40_standard', models.IntegerField(blank=True, null=True)),
                ('particles_40um', models.IntegerField(blank=True, null=True)),
                ('pm_temperature', models.FloatField(blank=True, null=True)),
                ('pm_humidity', models.FloatField(blank=True, null=True)),
                ('pm_voc_idx', models.FloatField(blank=True, null=True)),
                ('pm_nox_idx', models.FloatField(blank=True, null=True)),
                ('particles_tps', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Air quality metrics packet',
                'verbose_name_plural': 'Air quality metrics packets',
            },
            bases=('packets.rawpacket',),
        ),
        migrations.CreateModel(
            name='PowerMetricsPacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('reading_time', models.DateTimeField()),
                ('ch1_voltage', models.FloatField(blank=True, null=True)),
                ('ch1_current', models.FloatField(blank=True, null=True)),
                ('ch2_voltage', models.FloatField(blank=True, null=True)),
                ('ch2_current', models.FloatField(blank=True, null=True)),
                ('ch3_voltage', models.FloatField(blank=True, null=True)),
                ('ch3_current', models.FloatField(blank=True, null=True)),
                ('ch4_voltage', models.FloatField(blank=True, null=True)),
                ('ch4_current', models.FloatField(blank=True, null=True)),
                ('ch5_voltage', models.FloatField(blank=True, null=True)),
                ('ch5_current', models.FloatField(blank=True, null=True)),
                ('ch6_voltage', models.FloatField(blank=True, null=True)),
                ('ch6_current', models.FloatField(blank=True, null=True)),
                ('ch7_voltage', models.FloatField(blank=True, null=True)),
                ('ch7_current', models.FloatField(blank=True, null=True)),
                ('ch8_voltage', models.FloatField(blank=True, null=True)),
                ('ch8_current', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Power metrics packet',
                'verbose_name_plural': 'Power metrics packets',
            },
            bases=('packets.rawpacket',),
        ),
        migrations.CreateModel(
            name='HealthMetricsPacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('reading_time', models.DateTimeField()),
                ('heart_bpm', models.IntegerField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Health metrics packet',
                'verbose_name_plural': 'Health metrics packets',
            },
            bases=('packets.rawpacket',),
        ),
        migrations.CreateModel(
            name='HostMetricsPacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('reading_time', models.DateTimeField()),
                ('uptime_seconds', models.IntegerField(blank=True, null=True)),
                ('freemem_bytes', models.BigIntegerField(blank=True, null=True)),
                ('diskfree1_bytes', models.BigIntegerField(blank=True, null=True)),
                ('diskfree2_bytes', models.BigIntegerField(blank=True, null=True)),
                ('diskfree3_bytes', models.BigIntegerField(blank=True, null=True)),
                ('load1', models.IntegerField(blank=True, null=True)),
                ('load5', models.IntegerField(blank=True, null=True)),
                ('load15', models.IntegerField(blank=True, null=True)),
                ('user_string', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Host metrics packet',
                'verbose_name_plural': 'Host metrics packets',
            },
            bases=('packets.rawpacket',),
        ),
        migrations.CreateModel(
            name='TrafficManagementStatsPacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('reading_time', models.DateTimeField()),
                ('packets_inspected', models.IntegerField(blank=True, null=True)),
                ('position_dedup_drops', models.IntegerField(blank=True, null=True)),
                ('nodeinfo_cache_hits', models.IntegerField(blank=True, null=True)),
                ('rate_limit_drops', models.IntegerField(blank=True, null=True)),
                ('unknown_packet_drops', models.IntegerField(blank=True, null=True)),
                ('hop_exhausted_packets', models.IntegerField(blank=True, null=True)),
                ('router_hops_preserved', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Traffic management stats packet',
                'verbose_name_plural': 'Traffic management stats packets',
            },
            bases=('packets.rawpacket',),
        ),
    ]
