# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packets", "0009_new_telemetry_packet_models"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rawpacket",
            index=models.Index(fields=["from_int", "packet_id"], name="packets_raw_from_pkt_idx"),
        ),
    ]
