# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packets", "0010_add_from_int_packet_id_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodeinfopacket",
            name="is_licensed",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="nodeinfopacket",
            name="is_unmessagable",
            field=models.BooleanField(null=True),
        ),
    ]
