# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packets", "0011_add_nodeinfo_is_licensed_is_unmessagable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodeinfopacket",
            name="sw_version",
        ),
    ]
