# Generated by Django 5.2.12 on 2026-03-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0012_remove_nodeinfopacket_sw_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceroutePacket',
            fields=[
                ('rawpacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='packets.rawpacket')),
                ('route', models.JSONField(default=list, help_text='List of node_ids, path from source to dest')),
                ('route_back', models.JSONField(default=list, help_text='List of node_ids, path from dest back to source')),
            ],
            options={
                'verbose_name': 'Traceroute packet',
                'verbose_name_plural': 'Traceroute packets',
            },
            bases=('packets.rawpacket',),
        ),
    ]
