# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packets", "0013_add_traceroute_packet"),
    ]

    operations = [
        migrations.AddField(
            model_name="traceroutepacket",
            name="snr_towards",
            field=models.JSONField(
                default=list,
                help_text="SNR (dB) per hop for forward path. Scaled by 4 in protocol; stored as dB.",
            ),
        ),
        migrations.AddField(
            model_name="traceroutepacket",
            name="snr_back",
            field=models.JSONField(
                default=list,
                help_text="SNR (dB) per hop for return path. Scaled by 4 in protocol; stored as dB.",
            ),
        ),
    ]
