# Generated by Django 5.2.13 on 2026-04-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0005_add_bot_default_env_vars'),
        ('nodes', '0029_observednode_weather_classification'),
        ('packets', '0015_rename_packets_raw_from_pkt_idx_packets_raw_from_in_81757d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='packetobservation',
            index=models.Index(fields=['observer', 'upload_time'], name='packets_po_obs_upload_idx'),
        ),
    ]
