# Generated by Django 5.2.14 on 2026-05-18 14:38
#
# MTI parent rename: ``RenameModel`` + ``RenameField`` on ``*_ptr`` breaks
# ``state_forwards`` (FieldError / InvalidBasesError). We apply a single atomic
# state operation, then use ``SeparateDatabaseAndState`` so the physical DDL runs
# as standard operations against a clone of the pre-migration state (Django
# #26488 / #28243). See ``packets.migration_operations.RenameMeshtasticRawPacketMtiState``.

from django.db import migrations

from packets.migration_operations import (
    RenameMeshtasticRawPacketMtiState,
    packets_0017_separate_database_backwards,
    packets_0017_separate_database_forwards,
)


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0026_backfill_observednode_created_at"),
        ("packets", "0016_packetobservation_observer_upload_time_idx"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                RenameMeshtasticRawPacketMtiState(),
                migrations.AlterModelOptions(
                    name="mtrawpacket",
                    options={
                        "verbose_name": "Meshtastic raw packet",
                        "verbose_name_plural": "Meshtastic raw packets",
                    },
                ),
                migrations.RenameIndex(
                    model_name="mtrawpacket",
                    new_name="packets_mt__packet__aba474_idx",
                    old_name="packets_raw_packet__cc40c7_idx",
                ),
                migrations.RenameIndex(
                    model_name="mtrawpacket",
                    new_name="packets_mt__from_in_e6f943_idx",
                    old_name="packets_raw_from_in_3cd2a4_idx",
                ),
                migrations.RenameIndex(
                    model_name="mtrawpacket",
                    new_name="packets_mt__from_in_d78106_idx",
                    old_name="packets_raw_from_in_81757d_idx",
                ),
                migrations.RenameIndex(
                    model_name="mtrawpacket",
                    new_name="packets_mt__to_int_d08bdd_idx",
                    old_name="packets_raw_to_int_52668e_idx",
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    packets_0017_separate_database_forwards,
                    packets_0017_separate_database_backwards,
                    atomic=True,
                ),
            ],
        ),
    ]
