# Generated by Django 5.2.13 on 2026-04-25 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constellations', '0005_add_bot_default_env_vars'),
        ('nodes', '0032_add_update_managed_node_statuses_periodic_task'),
        ('packets', '0016_packetobservation_observer_upload_time_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DxNodeMetadata',
            fields=[
                ('observed_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dx_metadata', serialize=False, to='nodes.observednode')),
                ('exclude_from_detection', models.BooleanField(default=False, help_text='When True, this node is ignored by DX candidate detection.')),
                ('exclude_notes', models.TextField(blank=True, default='')),
                ('cluster_position_evaluated_for_dx', models.BooleanField(default=False, help_text='True after the first time the node had usable coordinates and a constellation cluster footprint existed for cluster-distance evaluation.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DX node metadata',
                'verbose_name_plural': 'DX node metadata',
            },
        ),
        migrations.CreateModel(
            name='DxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_code', models.CharField(choices=[('new_distant_node', 'New distant node'), ('returned_dx_node', 'Returned DX node'), ('distant_observation', 'Distant observation')], db_index=True, max_length=64)),
                ('state', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=16)),
                ('first_observed_at', models.DateTimeField()),
                ('last_observed_at', models.DateTimeField()),
                ('active_until', models.DateTimeField(db_index=True)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('best_distance_km', models.FloatField(blank=True, null=True)),
                ('last_distance_km', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dx_events', to='constellations.constellation')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dx_events', to='nodes.observednode')),
                ('last_observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dx_events_last_observed', to='nodes.managednode')),
            ],
            options={
                'verbose_name': 'DX event',
                'verbose_name_plural': 'DX events',
            },
        ),
        migrations.CreateModel(
            name='DxEventObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observed_at', models.DateTimeField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='dx_monitoring.dxevent')),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dx_event_observations', to='nodes.managednode')),
                ('packet_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dx_event_observations', to='packets.packetobservation')),
                ('raw_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dx_event_observations', to='packets.rawpacket')),
            ],
            options={
                'verbose_name': 'DX event observation',
                'verbose_name_plural': 'DX event observations',
            },
        ),
        migrations.AddIndex(
            model_name='dxevent',
            index=models.Index(fields=['constellation', 'destination', 'reason_code', 'active_until'], name='dx_event_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='dxeventobservation',
            index=models.Index(fields=['event', 'observed_at'], name='dx_evobs_event_time_idx'),
        ),
    ]
