# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dx_monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dxevent",
            name="reason_code",
            field=models.CharField(
                choices=[
                    ("new_distant_node", "New distant node"),
                    ("returned_dx_node", "Returned DX node"),
                    ("distant_observation", "Distant observation"),
                    ("traceroute_distant_hop", "Traceroute distant hop"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
