# Generated by Django 5.2.13 on 2026-04-27 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_explore_active_dx_events_task(apps, schema_editor):
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    schedule, _ = IntervalSchedule.objects.get_or_create(every=120, period="seconds")
    PeriodicTask.objects.get_or_create(
        name="explore_active_dx_events",
        defaults={
            "task": "dx_monitoring.tasks.explore_active_dx_events",
            "interval": schedule,
            "enabled": True,
        },
    )


def remove_explore_active_dx_events_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name="explore_active_dx_events").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0001_initial"),
        ("dx_monitoring", "0002_dxevent_reason_traceroute_distant_hop"),
        ("nodes", "0033_managednode_deleted_at"),
        ("traceroute", "0012_new_node_baseline_trigger_and_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name='DxEventTraceroute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('pending', 'Awaiting traceroute result'), ('completed', 'Traceroute completed successfully'), ('failed', 'Traceroute failed or timed out'), ('skipped', 'Did not queue a new traceroute')], db_index=True, default='pending', max_length=24)),
                ('skip_reason', models.CharField(blank=True, choices=[('no_eligible_source', 'No eligible source'), ('source_queue_full', 'Source pending queue full'), ('event_cooldown', 'Event exploration cooldown'), ('target_cooldown', 'Target exploration cooldown'), ('source_cooldown', 'Source exploration cooldown'), ('baseline_in_flight', 'Baseline traceroute already covers this source'), ('baseline_recent_success', 'Recent baseline completed for this source'), ('baseline_failure_cooldown', 'Baseline failed recently for this source'), ('duplicate_dx_watch', 'Existing DX_WATCH for this source and target'), ('destination_excluded', 'Destination excluded from DX'), ('fanout_saturated', 'Max exploration sources already covered for this event')], default='', max_length=48)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_traceroute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dx_event_traceroutes', to='traceroute.autotraceroute')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceroute_explorations', to='dx_monitoring.dxevent')),
                ('source_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dx_event_traceroutes', to='nodes.managednode')),
            ],
            options={
                'verbose_name': 'DX event traceroute exploration',
                'verbose_name_plural': 'DX event traceroute explorations',
                'indexes': [models.Index(fields=['event', 'created_at'], name='dx_evtr_event_created_idx'), models.Index(fields=['auto_traceroute'], name='dx_evtr_autotr_idx')],
            },
        ),
        migrations.RunPython(create_explore_active_dx_events_task, remove_explore_active_dx_events_task),
    ]
