# Generated by Django 5.2.13 on 2026-04-27 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dx_monitoring', '0003_dx_event_traceroute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DxNotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='When True and Discord is verified, the user can receive category-filtered DMs.')),
                ('all_categories', models.BooleanField(default=True, help_text='When True, all DX notification categories are included.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dx_notification_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DX notification subscription',
                'verbose_name_plural': 'DX notification subscriptions',
            },
        ),
        migrations.CreateModel(
            name='DxNotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('new_distant_node', 'New distant node'), ('returned_dx_node', 'Returned DX node after quiet period'), ('distant_observation', 'Distant direct/near-direct observation'), ('traceroute_distant_hop', 'Distant hop from traceroute evidence'), ('confirmed_event', 'Event reached evidence threshold'), ('event_closed_summary', 'Event closed (summary)')], db_index=True, max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='dx_monitoring.dxevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dx_notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DX notification delivery',
                'verbose_name_plural': 'DX notification deliveries',
                'indexes': [models.Index(fields=['user', 'category', 'created_at'], name='dx_notif_deliv_user_cat_time')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user', 'category'), name='dx_notif_deliv_event_user_category_uniq')],
            },
        ),
        migrations.CreateModel(
            name='DxNotificationCategorySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('new_distant_node', 'New distant node'), ('returned_dx_node', 'Returned DX node after quiet period'), ('distant_observation', 'Distant direct/near-direct observation'), ('traceroute_distant_hop', 'Distant hop from traceroute evidence'), ('confirmed_event', 'Event reached evidence threshold'), ('event_closed_summary', 'Event closed (summary)')], db_index=True, max_length=48)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_selections', to='dx_monitoring.dxnotificationsubscription')),
            ],
            options={
                'verbose_name': 'DX notification category selection',
                'verbose_name_plural': 'DX notification category selections',
                'constraints': [models.UniqueConstraint(fields=('subscription', 'category'), name='dx_notif_sub_cat_uniq')],
            },
        ),
    ]
