"""
Django settings for Meshflow project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Version information
VERSION = os.environ.get("APP_VERSION", "development")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_non_prod_secret_key = "django-insecure-fp!lzv7u#%2wn=0wno1&q-2bzz6=(9-sl6x@7w*-7g3mt#*i3z"
SECRET_KEY = os.environ.get("SECRET_KEY", _non_prod_secret_key)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "false") in ["True", "true", "1"]

SERVE_STATIC_FILES = os.environ.get("SERVE_STATIC_FILES", "false") in ["True", "true", "1"]

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]
for host in os.environ.get("ALLOWED_HOSTS", "meshcontrol.local").split(","):
    host = host.strip()
    if host:
        ALLOWED_HOSTS.append(host)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for django-allauth
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    # Channels
    "channels",
    # Authentication
    "allauth",
    "allauth.account",
    "allauth.headless",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.discord",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    # Project apps
    "Meshflow",
    "users",
    "push_notifications",
    "constellations",
    "nodes",
    "packets",
    "stats",
    "text_messages",
    "traceroute",
    "mesh_monitoring",
    "dx_monitoring",
    "ws",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "Meshflow.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Meshflow.wsgi.application"
ASGI_APPLICATION = "Meshflow.asgi.application"

# Logical DB allocation (single Redis server): Channels 0, Celery broker 1, Django cache 2 — see docs/REDIS.md
_redis_password = os.environ.get("REDIS_PASSWORD", "")
_redis_host = os.environ.get("REDIS_HOST", "localhost")
_redis_port = os.environ.get("REDIS_PORT", "6379")
_redis_url = f"redis://:{_redis_password}@{_redis_host}:{_redis_port}/0"

# Channel layers for Django Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [_redis_url],
        },
    },
}

# Neo4j (traceroute heatmap graph)
NEO4J_URI = os.environ.get("NEO4J_URI", "bolt://localhost:7687")
NEO4J_USER = os.environ.get("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = os.environ.get("NEO4J_PASSWORD", "neo4j")

# Celery (use Redis DB 1 for broker; channels use DB 0)
_celery_broker_url = f"redis://:{_redis_password}@{_redis_host}:{_redis_port}/1"
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", _celery_broker_url)
CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
# Route heavy RF propagation renders to a dedicated queue consumed by celery-rf-worker;
# keep the default "celery" queue so the existing worker picks up everything else.
CELERY_TASK_DEFAULT_QUEUE = "celery"
CELERY_TASK_ROUTES = {
    "nodes.tasks.render_rf_propagation": {"queue": "rf_renders"},
}

# RF propagation cached PNGs (on-disk; written by the Celery worker).
RF_PROPAGATION_ASSET_DIR = Path(
    os.environ.get("RF_PROPAGATION_ASSET_DIR", "/var/meshflow/generated-assets/rf-propagation")
)
# Meshtastic Site Planner engine base URL (FastAPI service, see deployment/docker-compose.yaml).
RF_PROPAGATION_ENGINE_URL = os.environ.get("RF_PROPAGATION_ENGINE_URL", "")
# Bump this to invalidate every cached render (pipeline or post-processing change).
RF_PROPAGATION_RENDER_VERSION = os.environ.get("RF_PROPAGATION_RENDER_VERSION", "4")


def _rf_propagation_nodata_rgb() -> tuple[int, int, int]:
    raw = os.environ.get("RF_PROPAGATION_NODATA_RGB", "0,0,0")
    try:
        parts = [int(x.strip()) for x in raw.split(",")]
        if len(parts) == 3 and all(0 <= p <= 255 for p in parts):
            return (parts[0], parts[1], parts[2])
    except ValueError:
        pass
    return (0, 0, 0)


# GeoTIFF coverage rasters use this colour for "no signal"; strip to transparent in PNG for map overlay.
RF_PROPAGATION_NODATA_RGB = _rf_propagation_nodata_rgb()
RF_PROPAGATION_NODATA_TOLERANCE = max(
    0,
    min(255, int(os.environ.get("RF_PROPAGATION_NODATA_TOLERANCE", "8"))),
)


def _rf_env_float(name: str, default: float) -> float:
    raw = os.environ.get(name)
    if raw is None or str(raw).strip() == "":
        return default
    return float(str(raw).strip())


def _rf_env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None or str(raw).strip() == "":
        return default
    return str(raw).strip().lower() in ("1", "true", "yes", "on")


# Default bbox radius around the tx (metres) when the profile does not specify one.
_rf_radius_raw = os.environ.get("RF_PROPAGATION_DEFAULT_RADIUS_M")
RF_PROPAGATION_DEFAULT_RADIUS_M = (
    int(str(_rf_radius_raw).strip()) if _rf_radius_raw and str(_rf_radius_raw).strip() else 50000
)
# Matplotlib colormap name passed to Site Planner (validated in rf_propagation.payload).
RF_PROPAGATION_COLORMAP = (
    os.environ.get("RF_PROPAGATION_COLORMAP").strip() if os.environ.get("RF_PROPAGATION_COLORMAP") else "plasma"
)
# SPLAT/site-planner: False = ~3 arc-sec SRTM, True = ~1 arc-sec (much larger rasters).
RF_PROPAGATION_HIGH_RESOLUTION = _rf_env_bool("RF_PROPAGATION_HIGH_RESOLUTION", False)
RF_PROPAGATION_MIN_DBM = _rf_env_float("RF_PROPAGATION_MIN_DBM", -130.0)
RF_PROPAGATION_MAX_DBM = _rf_env_float("RF_PROPAGATION_MAX_DBM", -50.0)
RF_PROPAGATION_SIGNAL_THRESHOLD_DBM = _rf_env_float("RF_PROPAGATION_SIGNAL_THRESHOLD_DBM", -110.0)
# Upper bound (seconds) for polling engine job status inside the Celery task.
RF_PROPAGATION_POLL_MAX_SECONDS = int(os.environ.get("RF_PROPAGATION_POLL_MAX_SECONDS", "300"))
# Per-node retention: how many ``ready`` renders to keep on disk before GC.
RF_PROPAGATION_READY_RETENTION = int(os.environ.get("RF_PROPAGATION_READY_RETENTION", "3"))

# Django cache (Redis DB 2; channels use DB 0, Celery broker DB 1)
_cache_url = f"redis://:{_redis_password}@{_redis_host}:{_redis_port}/2"
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": _cache_url,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "meshflow_preprod"),
        "USER": os.environ.get("POSTGRES_USER", "meshflow_preprod"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "meshflow_preprod"),
        "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/admin/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"
os.makedirs(STATIC_ROOT, exist_ok=True)
STATICFILES_DIRS = []
for d in STATICFILES_DIRS:
    os.makedirs(d, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "users.User"

# Packet deduplication: time window (minutes) within which same sender+packet_id is treated as duplicate
PACKET_DEDUP_WINDOW_MINUTES = int(os.environ.get("PACKET_DEDUP_WINDOW_MINUTES", "10"))

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.JWTAuthentication",
        # "rest_framework.authentication.SessionAuthentication",
        # "nodes.authentication.NodeAPIKeyAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "Meshflow.paginator.PageSizePagination",
}

# JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.environ.get("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", 1440))  # 24h default
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.environ.get("JWT_REFRESH_TOKEN_LIFETIME_DAYS", 30))),  # 30d default
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}

# django-allauth settings
SITE_ID = int(os.environ.get("SITE_ID", "1"))

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
]

# allauth settings
# ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
# ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*"]
ACCOUNT_LOGIN_METHODS = {"email", "username"}
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = "optional"
SOCIALACCOUNT_ADAPTER = "users.adapters.MergeByEmailSocialAccountAdapter"

# dj-rest-auth settings
REST_AUTH = {
    "USE_JWT": True,
    "JWT_AUTH_COOKIE": "meshflow-auth",
    "JWT_AUTH_REFRESH_COOKIE": "meshflow-refresh",
    "JWT_AUTH_SECURE": False,  # Set to True in production
    "JWT_AUTH_HTTPONLY": True,
    "JWT_AUTH_SAMESITE": "Lax",
    "SESSION_LOGIN": False,
    "USER_DETAILS_SERIALIZER": "users.serializers.UserSerializer",
}

CALLBACK_URL_BASE = os.environ.get("CALLBACK_URL_BASE", "http://localhost:8000").rstrip("/")

# Social authentication settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    },
    "github": {
        "APP": {
            "client_id": os.environ.get("GITHUB_CLIENT_ID", ""),
            "secret": os.environ.get("GITHUB_CLIENT_SECRET", ""),
        }
    },
    "discord": {
        "APP": {
            "client_id": os.environ.get("DISCORD_CLIENT_ID", ""),
            "secret": os.environ.get("DISCORD_CLIENT_SECRET", ""),
        },
        "SCOPE": ["identify", "email"],
    },
}

# Discord bot token for server-side DMs (Mesh Monitoring / test endpoint).
# This is separate from DISCORD_CLIENT_* used for OAuth login.
DISCORD_BOT_TOKEN = os.environ.get("DISCORD_BOT_TOKEN", "")

# HATE trailing slashes!
APPEND_SLASH = True

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173").rstrip("/")
FRONTEND_OAUTH_CALLBACK_PATH = os.environ.get("FRONTEND_OAUTH_CALLBACK_PATH", "/auth/callback")

LOGIN_URL = "/admin/login/"

# CORS settings
CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
    "http://localhost:5173",  # Vite dev server
    "http://127.0.0.1:5173",
]

for origin in os.environ.get("CORS_ALLOWED_ORIGINS", "").split(","):
    origin = origin.strip()
    if origin:
        CORS_ALLOWED_ORIGINS.append(origin)

CORS_ALLOW_CREDENTIALS = True

# CSRF - Django 4.0+ requires the full URL with scheme for origin checking.
# Separate from CORS: CSRF_TRUSTED_ORIGINS validates the Origin/Referer header on unsafe requests.
CSRF_TRUSTED_ORIGINS = []
for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(","):
    origin = origin.strip().rstrip("/")
    if origin:
        CSRF_TRUSTED_ORIGINS.append(origin)

# Add any additional CORS settings as needed
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


def _dx_env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None or str(raw).strip() == "":
        return default
    return str(raw).strip().lower() in ("1", "true", "yes", "on")


def _dx_env_int(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None or str(raw).strip() == "":
        return default
    return int(str(raw).strip())


def _dx_env_float(name: str, default: float) -> float:
    raw = os.environ.get(name)
    if raw is None or str(raw).strip() == "":
        return default
    return float(str(raw).strip())


# DX Monitoring candidate detection (packet ingestion; default off).
DX_MONITORING_DETECTION_ENABLED = _dx_env_bool("DX_MONITORING_DETECTION_ENABLED", False)
DX_MONITORING_RETURNED_DX_QUIET_DAYS = _dx_env_int("DX_MONITORING_RETURNED_DX_QUIET_DAYS", 30)
DX_MONITORING_EVENT_ACTIVE_MINUTES = _dx_env_int("DX_MONITORING_EVENT_ACTIVE_MINUTES", 60)
DX_MONITORING_CLUSTER_DISTANCE_KM = _dx_env_float("DX_MONITORING_CLUSTER_DISTANCE_KM", 150.0)
DX_MONITORING_DIRECT_DISTANCE_KM = _dx_env_float("DX_MONITORING_DIRECT_DISTANCE_KM", 100.0)

# Enable Prometheus metrics if a password is set
PROMETHEUS_PASSWORD = os.environ.get("PROMETHEUS_PASSWORD", None)
if PROMETHEUS_PASSWORD:
    INSTALLED_APPS.append("django_prometheus")
    MIDDLEWARE.insert(0, "django_prometheus.middleware.PrometheusBeforeMiddleware")
    MIDDLEWARE.append("Meshflow.middleware.MetricsAuthMiddleware")
    MIDDLEWARE.append("django_prometheus.middleware.PrometheusAfterMiddleware")

# Logging configuration for development
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "level": "INFO",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
