# Generated by Django 5.2.13 on 2026-04-15 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0029_observednode_weather_classification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePresence',
            fields=[
                ('observed_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mesh_presence', serialize=False, to='nodes.observednode')),
                ('verification_started_at', models.DateTimeField(blank=True, help_text='When the current verification traceroute round started.', null=True)),
                ('offline_confirmed_at', models.DateTimeField(blank=True, help_text='When the node was confirmed offline after failed verification.', null=True)),
            ],
            options={
                'verbose_name': 'Node presence (mesh monitoring)',
                'verbose_name_plural': 'Node presences (mesh monitoring)',
            },
        ),
        migrations.CreateModel(
            name='NodeWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offline_after', models.PositiveIntegerField(default=7200, help_text='Seconds without packets (last_heard) before verification may start.')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observed_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='nodes.observednode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Node watch',
                'verbose_name_plural': 'Node watches',
                'indexes': [models.Index(fields=['observed_node', 'enabled'], name='mesh_monito_observe_cb77be_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'observed_node'), name='mesh_monitoring_nodewatch_user_node_uniq')],
            },
        ),
    ]
