# Generated by Django 5.2.13 on 2026-04-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh_monitoring', '0002_add_process_node_watch_presence_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodepresence',
            name='last_tr_sent',
            field=models.DateTimeField(blank=True, help_text='When a monitoring traceroute command was last sent to the mesh for this target.', null=True),
        ),
        migrations.AddField(
            model_name='nodepresence',
            name='last_zero_sources_at',
            field=models.DateTimeField(blank=True, help_text='When dispatch last found no eligible managed sources for monitoring TR.', null=True),
        ),
        migrations.AddField(
            model_name='nodepresence',
            name='suspected_offline_at',
            field=models.DateTimeField(blank=True, help_text='When the current mesh-monitoring verification episode started (silence → TR round).', null=True),
        ),
        migrations.AddField(
            model_name='nodepresence',
            name='tr_sent_count',
            field=models.PositiveIntegerField(default=0, help_text='Monitoring TR sends in the current episode; reset when the node is considered online.'),
        ),
    ]
