# Generated by Django 5.2.13

from django.db import migrations, models


def backfill_is_offline(apps, schema_editor):
    NodePresence = apps.get_model("mesh_monitoring", "NodePresence")
    NodePresence.objects.filter(offline_confirmed_at__isnull=False).update(is_offline=True)


class Migration(migrations.Migration):

    dependencies = [
        ("mesh_monitoring", "0003_nodepresence_observability_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodepresence",
            name="is_offline",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True after mesh monitoring confirms the node offline (verification window expired). "
                    "Cleared when the node is heard again."
                ),
            ),
        ),
        migrations.AddField(
            model_name="nodepresence",
            name="observed_online_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When mesh monitoring last treated the node as online: initial create while heard, "
                    "or recovery after confirmed offline."
                ),
                null=True,
            ),
        ),
        migrations.RunPython(backfill_is_offline, migrations.RunPython.noop),
    ]
