# Generated by Django 5.2.13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mesh_monitoring", "0004_nodepresence_is_offline_observed_online_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodepresence",
            name="last_verification_notify_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When mesh monitoring last sent a Discord DM that verification (monitor TR) had started, "
                    "for cooldown against notify spam."
                ),
                null=True,
            ),
        ),
    ]
