# Generated by Django 5.2.13 on 2026-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh_monitoring', '0007_node_monitoring_config_battery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodepresence',
            name='battery_alert_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When battery alert episode was confirmed (N consecutive low reports); used for UI and dedupe.', null=True),
        ),
        migrations.AlterField(
            model_name='nodepresence',
            name='battery_alerting_since',
            field=models.DateTimeField(blank=True, help_text='When the current below-threshold streak started (first low report in episode).', null=True),
        ),
        migrations.AlterField(
            model_name='nodepresence',
            name='last_battery_alert_notify_at',
            field=models.DateTimeField(blank=True, help_text='When mesh monitoring last sent a low-battery Discord DM for this episode.', null=True),
        ),
        migrations.AlterField(
            model_name='nodepresence',
            name='last_battery_recovered_at',
            field=models.DateTimeField(blank=True, help_text='When battery last recovered above threshold.', null=True),
        ),
    ]
