# Generated by Django 5.2.14 on 2026-06-01 09:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constellations', '0011_remove_constellationusermembership'),
        ('nodes', '0050_managednode_protocol_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeshCorePathEdgeBucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bucket_start', models.DateTimeField(db_index=True)),
                ('bucket_size', models.CharField(default='1h', max_length=8)),
                ('from_kind', models.CharField(choices=[('hash', 'Hash'), ('node', 'Node'), ('feeder', 'Feeder'), ('unknown', 'Unknown')], default='hash', max_length=16)),
                ('to_kind', models.CharField(choices=[('hash', 'Hash'), ('node', 'Node'), ('feeder', 'Feeder'), ('unknown', 'Unknown')], default='hash', max_length=16)),
                ('from_hash', models.CharField(blank=True, default='', max_length=32)),
                ('to_hash', models.CharField(blank=True, default='', max_length=32)),
                ('packet_count', models.PositiveIntegerField(default=0)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('avg_snr', models.FloatField(blank=True, null=True)),
                ('min_snr', models.FloatField(blank=True, null=True)),
                ('max_snr', models.FloatField(blank=True, null=True)),
                ('constellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meshcore_path_edge_buckets', to='constellations.constellation')),
                ('from_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meshcore_path_edges_from', to='nodes.observednode')),
                ('observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meshcore_path_edge_buckets', to='nodes.managednode')),
                ('to_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meshcore_path_edges_to', to='nodes.observednode')),
            ],
            options={
                'verbose_name': 'MeshCore path edge bucket',
                'verbose_name_plural': 'MeshCore path edge buckets',
                'indexes': [models.Index(fields=['-bucket_start'], name='meshcore_pa_bucket__9276cc_idx'), models.Index(fields=['from_hash', 'to_hash'], name='meshcore_pa_from_ha_671731_idx')],
                'constraints': [models.UniqueConstraint(fields=('bucket_start', 'bucket_size', 'from_kind', 'to_kind', 'from_hash', 'to_hash', 'observer', 'constellation'), name='meshcore_path_edge_bucket_unique', nulls_distinct=False)],
            },
        ),
        migrations.CreateModel(
            name='MeshCorePathSegmentResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_hash', models.CharField(db_index=True, max_length=32)),
                ('hash_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hash_mode', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('resolved', 'Resolved'), ('ambiguous', 'Ambiguous'), ('stale', 'Stale')], db_index=True, default='unknown', max_length=16)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('resolver_version', models.PositiveIntegerField(default=1)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('observed_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meshcore_path_segments', to='nodes.observednode')),
            ],
            options={
                'verbose_name': 'MeshCore path segment resolution',
                'verbose_name_plural': 'MeshCore path segment resolutions',
                'indexes': [models.Index(fields=['-last_seen_at'], name='meshcore_pa_last_se_c35b9b_idx'), models.Index(fields=['status', '-last_seen_at'], name='meshcore_pa_status_6b0dba_idx')],
                'constraints': [models.UniqueConstraint(fields=('hash_mode', 'hash_size', 'segment_hash'), name='meshcore_path_segment_identity_unique')],
            },
        ),
    ]
