# Generated by Django 5.2.12 on 2026-03-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constellations', '0004_constellation_map_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('stat_type', models.CharField(db_index=True, max_length=20)),
                ('value', models.JSONField()),
                ('run_id', models.UUIDField(blank=True, null=True)),
                ('constellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats_snapshots', to='constellations.constellation')),
            ],
            options={
                'verbose_name': 'Stats snapshot',
                'verbose_name_plural': 'Stats snapshots',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['recorded_at', 'stat_type'], name='stats_stats_recorde_8bacca_idx'), models.Index(fields=['stat_type', 'constellation', 'recorded_at'], name='stats_stats_stat_ty_a67ba1_idx')],
            },
        ),
    ]
