# Generated by Django 5.2 on 2025-04-22 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.IntegerField()),
                ('voltage', models.FloatField()),
                ('channel_utilization', models.FloatField()),
                ('air_util_tx', models.FloatField()),
                ('uptime_seconds', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Device metrics',
                'verbose_name_plural': 'Device metrics',
            },
        ),
        migrations.CreateModel(
            name='ManagedNode',
            fields=[
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Managed node',
                'verbose_name_plural': 'Managed nodes',
            },
        ),
        migrations.CreateModel(
            name='NodeAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Node API Key',
                'verbose_name_plural': 'Node API Keys',
            },
        ),
        migrations.CreateModel(
            name='NodeAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Node authentication',
                'verbose_name_plural': 'Node authentications',
            },
        ),
        migrations.CreateModel(
            name='ObservedNode',
            fields=[
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.BigIntegerField()),
                ('mac_addr', models.CharField(blank=True, max_length=20, null=True)),
                ('long_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=5)),
                ('hw_model', models.CharField(blank=True, max_length=50, null=True)),
                ('sw_version', models.CharField(blank=True, max_length=12, null=True)),
                ('public_key', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Observed node',
                'verbose_name_plural': 'Observed nodes',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_time', models.DateTimeField()),
                ('reported_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('heading', models.FloatField()),
                ('location_source', models.IntegerField(choices=[(0, 'UNSET'), (1, 'LOC_MANUAL'), (2, 'LOC_INTERNAL'), (3, 'LOC_EXTERNAL')], default=0)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
    ]
