# Generated by Django 5.2 on 2025-04-22 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constellations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.IntegerField()),
                ('voltage', models.FloatField()),
                ('channel_utilization', models.FloatField()),
                ('air_util_tx', models.FloatField()),
                ('uptime_seconds', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Device metrics',
                'verbose_name_plural': 'Device metrics',
            },
        ),
        migrations.CreateModel(
            name='NodeAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Node API Key',
                'verbose_name_plural': 'Node API Keys',
            },
        ),
        migrations.CreateModel(
            name='NodeAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Node authentication',
                'verbose_name_plural': 'Node authentications',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_time', models.DateTimeField()),
                ('reported_time', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('heading', models.FloatField()),
                ('location_source', models.CharField(choices=[('0', 'Unset'), ('1', 'Manual'), ('2', 'Internal'), ('3', 'External')], default='0', max_length=1)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='MeshtasticNode',
            fields=[
                ('internal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.BigIntegerField()),
                ('mac_addr', models.CharField(blank=True, max_length=20, null=True)),
                ('long_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=5)),
                ('hw_model', models.CharField(blank=True, max_length=50, null=True)),
                ('sw_version', models.CharField(blank=True, max_length=12, null=True)),
                ('public_key', models.CharField(blank=True, max_length=64, null=True)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='constellations.constellation')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
            },
        ),
    ]
