# Generated by Django 5.2 on 2025-04-22 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constellations', '0002_initial'),
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meshtasticnode',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns this node', on_delete=django.db.models.deletion.CASCADE, related_name='owned_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nodeapikey',
            name='constellation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='constellations.constellation'),
        ),
        migrations.AddField(
            model_name='nodeapikey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nodeapikey',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='owned_api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nodeauth',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_links', to='nodes.nodeapikey'),
        ),
        migrations.AddField(
            model_name='nodeauth',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_key_links', to='nodes.meshtasticnode'),
        ),
        migrations.AddField(
            model_name='position',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_node_item_list', to='nodes.meshtasticnode'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeauth',
            unique_together={('api_key', 'node')},
        ),
    ]
