# Generated by Django 5.2 on 2025-04-22 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_alter_meshtasticnode_options_alter_position_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='meshtasticnode',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns this node', on_delete=django.db.models.deletion.CASCADE, related_name='owned_nodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
