# Generated by Django 5.2 on 2025-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='location_source',
            field=models.IntegerField(choices=[(0, 'Unset'), (1, 'Manual'), (2, 'Internal'), (3, 'External')], default=0),
        ),
    ]
