# Generated by Django 5.2 on 2025-04-22 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0002_initial'),
        ('nodes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observednode',
            name='constellation',
        ),
        migrations.AddField(
            model_name='managednode',
            name='constellation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='constellations.constellation'),
            preserve_default=False,
        ),
    ]
