# Generated by Django 5.2 on 2025-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_alter_position_location_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='location_source',
            field=models.IntegerField(choices=[(0, 'UNSET'), (1, 'LOC_MANUAL'), (2, 'LOC_INTERNAL'), (3, 'LOC_EXTERNAL')], default=0),
        ),
    ]
