# Generated by Django 5.2 on 2025-04-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_remove_observednode_constellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managednode',
            name='name',
            field=models.CharField(default='Node', max_length=100),
            preserve_default=False,
        ),
    ]
