# Generated by Django 5.2 on 2025-04-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_managednode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='ground_speed',
            field=models.FloatField(blank=True, help_text='Speed in m/s', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='ground_track',
            field=models.FloatField(blank=True, help_text='Track in degrees (0-359)', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='pdop',
            field=models.FloatField(blank=True, help_text='Position Dilution of Precision', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='precision_bits',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='sats_in_view',
            field=models.SmallIntegerField(blank=True, help_text='Number of satellites in view', null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='heading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
