# Generated by Django 5.2 on 2025-04-22 20:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_position_ground_speed_position_ground_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemetrics',
            name='logged_time',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemetrics',
            name='node',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nodes.observednode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemetrics',
            name='reported_time',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicemetrics',
            name='air_util_tx',
            field=models.FloatField(help_text='Air utilization for transmission'),
        ),
        migrations.AlterField(
            model_name='devicemetrics',
            name='battery_level',
            field=models.FloatField(help_text='Battery level as a percentage'),
        ),
        migrations.AlterField(
            model_name='devicemetrics',
            name='channel_utilization',
            field=models.FloatField(help_text='Channel utilization as a percentage'),
        ),
        migrations.AlterField(
            model_name='devicemetrics',
            name='uptime_seconds',
            field=models.BigIntegerField(help_text='Device uptime in seconds'),
        ),
        migrations.AlterField(
            model_name='devicemetrics',
            name='voltage',
            field=models.FloatField(help_text='Battery voltage in volts'),
        ),
        migrations.AlterField(
            model_name='position',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.observednode'),
        ),
    ]
