# Generated by Django 5.2 on 2025-04-23 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_devicemetrics_logged_time_devicemetrics_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemetrics',
            name='logged_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devicemetrics',
            name='reported_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='position',
            name='logged_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='position',
            name='reported_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
