# Generated by Django 5.2 on 2025-04-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_remove_nodeapikey_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='observednode',
            name='last_heard',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
