# Generated by Django 5.2 on 2025-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_observednode_last_heard'),
    ]

    operations = [
        migrations.AddField(
            model_name='observednode',
            name='node_id_str',
            field=models.CharField(db_index=True, default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observednode',
            name='node_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
