# Generated by Django 5.2 on 2025-05-02 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_observednode_node_id_str_alter_observednode_node_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observednode',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='The user who owns this node', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimed_nodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NodeOwnerClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.observednode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
