# Generated by Django 5.2 on 2025-05-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0003_messagechannel'),
        ('nodes', '0011_observednode_claimed_by_nodeownerclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='managednode',
            name='channel_0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AddField(
            model_name='managednode',
            name='channel_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AddField(
            model_name='managednode',
            name='channel_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AddField(
            model_name='managednode',
            name='channel_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AddField(
            model_name='managednode',
            name='channel_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AddField(
            model_name='managednode',
            name='channel_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AddField(
            model_name='managednode',
            name='channel_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AddField(
            model_name='managednode',
            name='channel_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
    ]
