# Generated by Django 5.2 on 2025-05-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0012_managednode_channel_0_managednode_channel_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observednode',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'CLIENT'), (1, 'CLIENT_MUTE'), (2, 'CLIENT_HIDDEN'), (3, 'TRACKER'), (4, 'LOST_AND_FOUND'), (5, 'SENSOR'), (6, 'TAK'), (7, 'TAK_TRACKER'), (8, 'REPEATER'), (9, 'ROUTER'), (10, 'ROUTER_LATE')], null=True),
        ),
    ]
