# Generated by Django 5.2 on 2025-05-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0013_observednode_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='managednode',
            name='default_location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managednode',
            name='default_location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
