# Generated by Django 5.2 on 2025-05-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0014_managednode_default_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managednode',
            name='node_id',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
