# Generated by Django 5.2 on 2025-05-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0015_alter_managednode_node_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devicemetrics',
            index=models.Index(fields=['node', '-logged_time'], name='idx_node_latest_device_metrics'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['node', '-logged_time'], name='idx_node_latest_position'),
        ),
    ]
