# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0016_devicemetrics_idx_node_latest_device_metrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLatestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('location_source', models.IntegerField(
                    blank=True,
                    choices=[
                        (0, 'UNSET'),
                        (1, 'LOC_MANUAL'),
                        (2, 'LOC_INTERNAL'),
                        (3, 'LOC_EXTERNAL'),
                    ], null=True)),
                ('precision_bits', models.SmallIntegerField(blank=True, null=True)),
                ('ground_speed', models.FloatField(blank=True, null=True)),
                ('ground_track', models.FloatField(blank=True, null=True)),
                ('sats_in_view', models.SmallIntegerField(blank=True, null=True)),
                ('pdop', models.FloatField(blank=True, null=True)),
                ('position_reported_time', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('channel_utilization', models.FloatField(blank=True, null=True)),
                ('air_util_tx', models.FloatField(blank=True, null=True)),
                ('uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('metrics_reported_time', models.DateTimeField(blank=True, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_status', to='nodes.observednode')),
            ],
            options={
                'verbose_name': 'Node latest status',
                'verbose_name_plural': 'Node latest statuses',
            },
        ),
    ]
