# Generated by Django 5.2

from django.db import migrations


def backfill_nodelateststatus(apps, schema_editor):
    """Backfill NodeLatestStatus from latest Position and DeviceMetrics per ObservedNode."""
    ObservedNode = apps.get_model('nodes', 'ObservedNode')
    NodeLatestStatus = apps.get_model('nodes', 'NodeLatestStatus')
    Position = apps.get_model('nodes', 'Position')
    DeviceMetrics = apps.get_model('nodes', 'DeviceMetrics')

    for node in ObservedNode.objects.all():
        latest_position = (
            Position.objects.filter(node=node).order_by('-reported_time').first()
        )
        latest_metrics = (
            DeviceMetrics.objects.filter(node=node).order_by('-reported_time').first()
        )

        if latest_position or latest_metrics:
            defaults = {}
            if latest_position:
                defaults.update(
                    latitude=latest_position.latitude,
                    longitude=latest_position.longitude,
                    altitude=latest_position.altitude,
                    heading=latest_position.heading,
                    location_source=latest_position.location_source,
                    precision_bits=latest_position.precision_bits,
                    ground_speed=latest_position.ground_speed,
                    ground_track=latest_position.ground_track,
                    sats_in_view=latest_position.sats_in_view,
                    pdop=latest_position.pdop,
                    position_reported_time=latest_position.reported_time,
                )
            if latest_metrics:
                defaults.update(
                    battery_level=latest_metrics.battery_level,
                    voltage=latest_metrics.voltage,
                    channel_utilization=latest_metrics.channel_utilization,
                    air_util_tx=latest_metrics.air_util_tx,
                    uptime_seconds=latest_metrics.uptime_seconds,
                    metrics_reported_time=latest_metrics.reported_time,
                )

            NodeLatestStatus.objects.update_or_create(node=node, defaults=defaults)


def noop(apps, schema_editor):
    """Reverse migration does nothing - NodeLatestStatus is repopulated on packet ingest."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0017_add_nodelateststatus'),
    ]

    operations = [
        migrations.RunPython(backfill_nodelateststatus, noop),
    ]
