# Generated by Django 5.2.12 on 2026-03-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0018_backfill_nodelateststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observednode',
            name='role',
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, 'CLIENT'), 
                    (1, 'CLIENT_MUTE'),
                    (2, 'ROUTER'),
                    (3, 'ROUTER_CLIENT'),  # deprecated
                    (4, 'REPEATER'),  # deprecated
                    (5, 'TRACKER'),
                    (6, 'SENSOR'),
                    (7, 'TAK'),
                    (8, 'CLIENT_HIDDEN'),
                    (9, 'LOST_AND_FOUND'),
                    (10, 'TAK_TRACKER'),
                    (11, 'ROUTER_LATE'),
                    (12, 'CLIENT_BASE'),
                ],
                null=True,
            ),
        ),
    ]
