# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0019_alter_observednode_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observednode',
            name='last_heard',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
