# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0021_telemetry_metrics_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="observednode",
            name="is_licensed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observednode",
            name="is_unmessagable",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
