# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0022_add_observednode_is_licensed_is_unmessagable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observednode",
            name="sw_version",
        ),
    ]
