# Generated by Django 5.2.12 on 2026-03-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0023_remove_observednode_sw_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='managednode',
            name='allow_auto_traceroute',
            field=models.BooleanField(default=False, help_text='If True, this node may be used for auto-scheduled traceroutes and manual triggers.'),
        ),
    ]
