# Generated by Django 5.2.12 on 2026-03-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0024_add_managednode_allow_auto_traceroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='observednode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
