# Generated by Django 5.2.12 on 2026-03-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0026_backfill_observednode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch1_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch1_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch2_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch2_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch3_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch3_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch4_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch4_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch5_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch5_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch6_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch6_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch7_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch7_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch8_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='ch8_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='environment_gas_resistance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='environment_iaq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='environment_lux',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='environment_radiation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='environment_rainfall_1h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='environment_rainfall_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='environment_wind_direction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='environment_wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodelateststatus',
            name='power_reported_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
