# Generated by Django 5.2.12 on 2026-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0027_extend_nodelateststatus_env_and_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodelateststatus',
            name='inferred_max_hops',
            field=models.SmallIntegerField(blank=True, help_text="Inferred from packet hop_start when received; the node's max hops setting.", null=True),
        ),
    ]
