# Generated by Django 5.2.12 on 2026-04-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0028_add_nodelateststatus_inferred_max_hops'),
    ]

    operations = [
        migrations.AddField(
            model_name='observednode',
            name='environment_exposure',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'indoor'), (2, 'outdoor'), (3, 'sheltered')], db_index=True, default=0, help_text='Physical placement of environment sensors (for weather suitability).'),
        ),
        migrations.AddField(
            model_name='observednode',
            name='weather_use',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'include'), (2, 'exclude')], db_index=True, default=0, help_text='Include or exclude from weather-style views.'),
        ),
    ]
