# Generated by Django 5.2.13 on 2026-04-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0029_observednode_weather_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeRfProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_latitude', models.FloatField(blank=True, null=True)),
                ('rf_longitude', models.FloatField(blank=True, null=True)),
                ('rf_altitude_m', models.FloatField(blank=True, null=True)),
                ('antenna_height_m', models.FloatField(blank=True, null=True)),
                ('antenna_gain_dbi', models.FloatField(blank=True, null=True)),
                ('tx_power_dbm', models.FloatField(blank=True, null=True)),
                ('rf_frequency_mhz', models.FloatField(blank=True, null=True)),
                ('antenna_pattern', models.CharField(choices=[('omni', 'Omni'), ('directional', 'Directional')], default='omni', max_length=20)),
                ('antenna_azimuth_deg', models.FloatField(blank=True, null=True)),
                ('antenna_beamwidth_deg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rf_profile', to='nodes.observednode')),
            ],
            options={
                'verbose_name': 'Node RF profile',
                'verbose_name_plural': 'Node RF profiles',
            },
        ),
        migrations.CreateModel(
            name='NodeRfPropagationRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('asset_filename', models.CharField(blank=True, max_length=256, null=True)),
                ('bounds_west', models.FloatField(blank=True, null=True)),
                ('bounds_south', models.FloatField(blank=True, null=True)),
                ('bounds_east', models.FloatField(blank=True, null=True)),
                ('bounds_north', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('observed_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rf_renders', to='nodes.observednode')),
            ],
            options={
                'verbose_name': 'Node RF propagation render',
                'verbose_name_plural': 'Node RF propagation renders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['observed_node', '-created_at'], name='idx_rf_render_node_created')],
            },
        ),
    ]
