# Generated by Django 5.2.13 on 2026-04-24 21:05

import django.db.models.deletion
from datetime import timedelta

from django.db import migrations, models
from django.db.models import Max
from django.utils import timezone


def backfill_managed_node_status(apps, schema_editor):
    """Create one ManagedNodeStatus per ManagedNode from PacketObservation aggregates."""
    ManagedNode = apps.get_model("nodes", "ManagedNode")
    ManagedNodeStatus = apps.get_model("nodes", "ManagedNodeStatus")
    PacketObservation = apps.get_model("packets", "PacketObservation")

    # Match default in nodes.managed_node_liveness (env not applied during migrations).
    default_recency_seconds = 600
    cutoff = timezone.now() - timedelta(seconds=default_recency_seconds)
    now = timezone.now()

    last_by_observer = dict(
        PacketObservation.objects.values("observer_id")
        .annotate(m=Max("upload_time"))
        .values_list("observer_id", "m")
    )

    to_create = []
    for mn in ManagedNode.objects.all().iterator(chunk_size=500):
        last = last_by_observer.get(mn.pk)
        is_sending = last is not None and last >= cutoff
        to_create.append(
            ManagedNodeStatus(
                node_id=mn.pk,
                last_packet_ingested_at=last,
                is_sending_data=is_sending,
                updated_at=now,
            )
        )
    if to_create:
        ManagedNodeStatus.objects.bulk_create(to_create, batch_size=500)


def reverse_backfill_managed_node_status(apps, schema_editor):
    ManagedNodeStatus = apps.get_model("nodes", "ManagedNodeStatus")
    ManagedNodeStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0030_node_rf_profile_and_propagation_render"),
        ("packets", "0016_packetobservation_observer_upload_time_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedNodeStatus",
            fields=[
                (
                    "node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="status",
                        serialize=False,
                        to="nodes.managednode",
                    ),
                ),
                (
                    "last_packet_ingested_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Latest PacketObservation.upload_time for this observer (API ingest time).",
                        null=True,
                    ),
                ),
                (
                    "is_sending_data",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when last_packet_ingested_at is within the configured feeder recency window.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Managed node status",
                "verbose_name_plural": "Managed node statuses",
            },
        ),
        migrations.RunPython(backfill_managed_node_status, reverse_backfill_managed_node_status),
    ]
