# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0032_add_update_managed_node_statuses_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="managednode",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When set, this managed node was soft-deleted and no longer participates in ingest or listings.",
                null=True,
            ),
        ),
    ]
