# Generated by Django 5.2.14 on 2026-05-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0007_protocol_help_text_managed_channels'),
        ('nodes', '0034_protocol_fields_observednode_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managednode',
            name='channel_0',
            field=models.ForeignKey(blank=True, help_text='Meshtastic channel slot 0 (PSK-backed MessageChannel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AlterField(
            model_name='managednode',
            name='channel_1',
            field=models.ForeignKey(blank=True, help_text='Meshtastic channel slot 1 (PSK-backed MessageChannel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AlterField(
            model_name='managednode',
            name='channel_2',
            field=models.ForeignKey(blank=True, help_text='Meshtastic channel slot 2 (PSK-backed MessageChannel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AlterField(
            model_name='managednode',
            name='channel_3',
            field=models.ForeignKey(blank=True, help_text='Meshtastic channel slot 3 (PSK-backed MessageChannel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AlterField(
            model_name='managednode',
            name='channel_4',
            field=models.ForeignKey(blank=True, help_text='Meshtastic channel slot 4 (PSK-backed MessageChannel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AlterField(
            model_name='managednode',
            name='channel_5',
            field=models.ForeignKey(blank=True, help_text='Meshtastic channel slot 5 (PSK-backed MessageChannel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AlterField(
            model_name='managednode',
            name='channel_6',
            field=models.ForeignKey(blank=True, help_text='Meshtastic channel slot 6 (PSK-backed MessageChannel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AlterField(
            model_name='managednode',
            name='channel_7',
            field=models.ForeignKey(blank=True, help_text='Meshtastic channel slot 7 (PSK-backed MessageChannel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constellations.messagechannel'),
        ),
        migrations.AlterField(
            model_name='managednode',
            name='protocol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Meshtastic'), (2, 'MeshCore')], db_index=True, default=1, help_text='Mesh protocol for this managed node (constellation must match).'),
        ),
        migrations.AlterField(
            model_name='observednode',
            name='node_id_str',
            field=models.CharField(db_index=True, help_text='Meshtastic display id (!hex or ^all); MeshCore display ids arrive in a later phase.', max_length=9),
        ),
        migrations.AlterField(
            model_name='observednode',
            name='protocol',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Meshtastic'), (2, 'MeshCore')], db_index=True, default=1, help_text='Mesh protocol for this observed node.'),
        ),
    ]
