# Generated by Django 5.2.14 on 2026-05-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0036_observednode_mc_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodelateststatus',
            name='inferred_max_hops',
            field=models.SmallIntegerField(blank=True, help_text="Meshtastic-only: inferred from packet hop_start when received; the node's max hops setting.", null=True),
        ),
        migrations.AlterField(
            model_name='observednode',
            name='long_name',
            field=models.CharField(help_text='Display name (long); populated for both Meshtastic and MeshCore from ingest.', max_length=50),
        ),
        migrations.AlterField(
            model_name='observednode',
            name='mac_addr',
            field=models.CharField(blank=True, help_text='Meshtastic nodeinfo MAC when protocol is Meshtastic; usually null for MeshCore.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='observednode',
            name='node_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Meshtastic numeric node id when protocol is Meshtastic; null for MeshCore.', null=True),
        ),
        migrations.AlterField(
            model_name='observednode',
            name='public_key',
            field=models.CharField(blank=True, help_text='Meshtastic device public key (PKI hex); null for MeshCore.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='observednode',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'CLIENT'), (1, 'CLIENT_MUTE'), (2, 'ROUTER'), (3, 'ROUTER_CLIENT'), (4, 'REPEATER'), (5, 'TRACKER'), (6, 'SENSOR'), (7, 'TAK'), (8, 'CLIENT_HIDDEN'), (9, 'LOST_AND_FOUND'), (10, 'TAK_TRACKER'), (11, 'ROUTER_LATE'), (12, 'CLIENT_BASE')], help_text='Meshtastic role (RoleSource); null for MeshCore.', null=True),
        ),
        migrations.AlterField(
            model_name='observednode',
            name='short_name',
            field=models.CharField(help_text='Display name (short); populated for both Meshtastic and MeshCore from ingest.', max_length=5),
        ),
    ]
