# Generated by Django 5.2.14 on 2026-05-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshcore_packets', '0002_rename_meshcore_raw_prefix_hash_idx_meshcore_pa_from_pu_8e7820_idx_and_more'),
        ('nodes', '0044_remove_observednode_node_id_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodelateststatus',
            name='meshcore_location_source',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ADVERT')], help_text='MeshCore-only: how the latest position was obtained (e.g. ADVERT decode).', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='meshcore_location_source',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ADVERT')], help_text='MeshCore-only: how this position sample was obtained.', null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='original_mc_packet',
            field=models.ForeignKey(blank=True, help_text='Provenance: MeshCore ingest packet that produced this position row.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='meshcore_packets.meshcorerawpacket'),
        ),
    ]
