# Generated by Django 5.2.14 on 2026-05-21 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0009_messagechannel_mc_type_hashtag'),
        ('nodes', '0046_managednode_mc_channels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managednode',
            name='mc_pubkey',
            field=models.CharField(blank=True, db_index=True, help_text='MeshCore feeder device pubkey (64-char lowercase hex). Required when multiple feeders share a constellation API key.', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='managednode',
            constraint=models.UniqueConstraint(condition=models.Q(('protocol', 2), ('mc_pubkey__isnull', False)), fields=('constellation', 'mc_pubkey'), name='managednode_unique_mc_pubkey_per_constellation'),
        ),
    ]
