# Generated by Django 5.2.14 on 2026-05-25 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0048_observednode_meshcore_adv_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='managednode',
            name='mc_flood_advert_interval_hours',
            field=models.PositiveSmallIntegerField(default=6, help_text='MeshCore feeder: hours between flood-routed advertisements sent by the bot.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
