# Generated by Django 5.2.14 on 2026-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0051_mc_canonical_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='observednode',
            name='m2m_opt_out',
            field=models.BooleanField(default=False, help_text='When set, this node is omitted from per-node M2M listings. Aggregates still count it.'),
        ),
    ]
