# Generated by Django 5.2.13 on 2026-04-27 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordNotificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempted_at', models.DateTimeField(blank=True, help_text='When a Discord API send was attempted (null for pre-send skips).', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When Discord accepted the message (only for sent).', null=True)),
                ('feature', models.CharField(choices=[('node_watch', 'Node watch (mesh monitoring)'), ('dx_monitoring', 'DX monitoring')], db_index=True, max_length=32)),
                ('kind', models.CharField(choices=[('node_offline', 'Node offline (after verification)'), ('verification_started', 'Mesh monitoring verification started')], db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('discord_recipient_id', models.CharField(blank=True, help_text='Discord snowflake used or proposed for the DM, when known.', max_length=32)),
                ('reason', models.TextField(blank=True, help_text='Skip or failure explanation.')),
                ('message_preview', models.CharField(blank=True, help_text='Truncated message body for admin review.', max_length=500)),
                ('related_app_label', models.CharField(blank=True, max_length=64)),
                ('related_model_name', models.CharField(blank=True, max_length=64)),
                ('related_object_id', models.CharField(blank=True, help_text='Primary key of the related row as string (supports non-int PKs).', max_length=64)),
                ('related_context', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discord_notification_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discord notification audit',
                'verbose_name_plural': 'Discord notification audits',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='push_notifi_created_72459b_idx'), models.Index(fields=['user', 'status', 'created_at'], name='push_notifi_user_id_8ac24e_idx'), models.Index(fields=['feature', 'kind', 'created_at'], name='push_notifi_feature_5efd3c_idx')],
            },
        ),
    ]
