# Generated by Django 5.2.13 on 2026-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_discord_notification_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordnotificationaudit',
            name='kind',
            field=models.CharField(choices=[('node_offline', 'Node offline (after verification)'), ('verification_started', 'Mesh monitoring verification started'), ('node_battery_low', 'Node battery low (mesh monitoring)'), ('dx_new_distant_node', 'DX: new distant node'), ('dx_returned_node', 'DX: returned node after quiet period'), ('dx_distant_observation', 'DX: distant direct observation'), ('dx_traceroute_distant_hop', 'DX: distant hop from traceroute'), ('dx_confirmed_event', 'DX: event reached evidence threshold'), ('dx_event_closed_summary', 'DX: event closed summary')], db_index=True, max_length=64),
        ),
    ]
