name: docker-build-and-push

on:
  workflow_call:
    inputs:
      VERSION_LABEL:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
        options:
          - dev
          - preprod
          - prod

permissions:
  contents: read
  packages: write


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
        include:
          - platform: linux/amd64
            base_image: "python:3.12"
          - platform: linux/arm64
            base_image: "arm64v8/python:3.12"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup vars
        run: |
          PLATFORM_TAG=$(echo "${{ matrix.platform }}" | sed 's|/|-|g')
          echo "PLATFORM_TAG=$PLATFORM_TAG" >> $GITHUB_ENV
          # Set LATEST_TAG and LATEST_MIGRATIONS_TAG based on ENVIRONMENT
          if [[ "${{ inputs.ENVIRONMENT }}" == "dev" ]]; then
            echo "LATEST_TAG=latest-dev" >> $GITHUB_ENV
            echo "LATEST_MIGRATIONS_TAG=latest-dev-migrations" >> $GITHUB_ENV
          elif [[ "${{ inputs.ENVIRONMENT }}" == "preprod" ]]; then
            echo "LATEST_TAG=latest-rc" >> $GITHUB_ENV
            echo "LATEST_MIGRATIONS_TAG=latest-rc-migrations" >> $GITHUB_ENV
          elif [[ "${{ inputs.ENVIRONMENT }}" == "prod" ]]; then
            echo "LATEST_TAG=latest" >> $GITHUB_ENV
            echo "LATEST_MIGRATIONS_TAG=latest-migrations" >> $GITHUB_ENV
          else
            echo "LATEST_TAG=" >> $GITHUB_ENV
            echo "LATEST_MIGRATIONS_TAG=" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}-${{ env.PLATFORM_TAG }}
          build-args: |
            VERSION=${{ inputs.VERSION_LABEL }}
            BASE_IMAGE=${{ matrix.base_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Migrations Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: ${{ matrix.platform }}
          file: Dockerfile-migrations
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.LATEST_MIGRATIONS_TAG }}-${{ env.PLATFORM_TAG }}
          build-args: |
            VERSION=${{ inputs.VERSION_LABEL }}
            BASE_IMAGE=${{ matrix.base_image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-manifest:
    runs-on: ubuntu-latest
    needs:
    - build-and-push

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Version Manifest
        run: |
          docker buildx imagetools create \
            -t ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }} \
            ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}-linux-amd64 \
            ghcr.io/${{ github.repository }}:${{ env.LATEST_TAG }}-linux-arm64

          docker buildx imagetools create \
            -t ghcr.io/${{ github.repository }}:${{ env.LATEST_MIGRATIONS_TAG }} \
            ghcr.io/${{ github.repository }}:${{ env.LATEST_MIGRATIONS_TAG }}-linux-amd64 \
            ghcr.io/${{ github.repository }}:${{ env.LATEST_MIGRATIONS_TAG }}-linux-arm64 